### ISSUE TITLE
cache udp server resync

### ISSUE THREAD

**Issue by prymitive** [unbit/uwsgi#101]
Would it be possible if one cache node could ask another node for all cache keys? For example one node would send some message to another node and this node would respond by sending cache updates for all keys it has. So that when new nodes starts it could replicate all keys from already running nodes.
Right now adding new node requires all nodes restart (we need to update --cache-udp-node configuration) but in the future node list might be fetched from routers or clusters, so it would be handy to have a way of adding new node.

**Comment by alanjds** [comment]
Hi. Is possible to trigger this sync without restarting, maybe via periodic mules/spoolers/etc? This way one can handle network partitions.

If I can combine some conflict resolution, as newest-hit-wins, or maybe on a custom user-function, then I could ditch Redis away for volatile data...

**Comment by unbit** [comment]
@alanjds i think the redis clustering system is way more advanced and solid than uWSGI caching sync (that is born to synchronize ssl data where a cache miss is not desruptive). Which is your specific use case ?

**Comment by alanjds** [comment]
You are right. Redis is the right tool. But my app was optimized for latency and uses uwsgi because of that. I tested with Redis but it lost ~15% of max throughput figure and ~1.5ms of latency because uwsgi is so damn fast as in-memory cache for low volumes of data!

I have some application that can survive main DB outages if the Cache is available. If the cache is always on sync, I can set the keys TTL to "forever" and just trigger updates when DB changes.

Well... right now I have 2+ app servers in load balance, using uwsgi cache. But when the DB changes, one app have no way to sync to another, so I need a TTL to the keys. This has made as latency optimization only. It is way faster to answer, but takes up to the TTL for the DB changes to propagate to all servers. And if DB is down, the system survives up to the TTL only.

I made a PoC with Redis instead of the uwsgi cache. On DB changes, update a remote Redis Master, that updates an instance of local Redis Slave on each app server. Apps connect to localhost Redis Slave for optimal latency, and it worked very well. DB updates are instant and DB outages render read-only working of the whole system. Very acceptable at our scenario!

But Redis costs ~15% of max throughput figure and ~1.5ms of extra latency, compared to uwsgi baseline.

I could set uwsgi ``cache-udp-server`` to each app server, so one app updating the DB (and own cache) would propagate to other servers. But if some UDP package got lost, this update will never be propagated to the other server. I can cope with eventual consistency of the cache if I can have a recurring scheduled resync of the caches ;) And a newest-write-wins is right as conflict resolution on my case, assuming that the servers are NTP synced.

**Comment by unbit** [comment]
@alanjds it is an interesting use case indeed, and considering you do not have huge amount of data to sync it could work really well. I will check if it is an easy addition otherwise be prepared for some form of sponsorship :)

**Comment by alanjds** [comment]
Nice (and thanks). I would like to contribute some code, but had not a grip on how things works internally. If I can have an overview on this I would prefer to give you a PR instead of unpaid hours of opensource work next time ;)

Anyway, I use this for so long that at least a tip is more than fair no matter what.
