### ISSUE TITLE
unavailable modifier requested

### ISSUE THREAD

**Issue by yueyoum** [unbit/uwsgi#1032]
I found this unusual message in uwsgi log:

```
-- unavailable modifier requested: 128 --
-- unavailable modifier requested: 22 --
Empty python request. skip.
[pid: 28620|app: -1|req: -1/77]  () {0 vars in 0 bytes} [Sun Sep  6 18:04:28 2015]   => generated 0 bytes in 0 msecs ( 0) 0 headers in 0 bytes (0 
switches on core 0)
-- unavailable modifier requested: 3 --
-- unavailable modifier requested: 58 --
-- unavailable modifier requested: 1 --
```

How this happened ?

**Comment by xrmx** [comment]
@yueyoum this is a request for support not a uwsgi issue so better ask on mailing list please. The wiki gives some hints about the "unavailable modifier requested" here http://uwsgi-docs.readthedocs.org/en/latest/ThingsToKnow.html . Also please always post your config file otherwise it's very hard to help. thanks.

**Comment by xrmx** [comment]
No update from reporter in a month, closing.
