### ISSUE TITLE
Chunked input to openstack glance fails with no data

### ISSUE THREAD

**Issue by bjne** [unbit/uwsgi#1187]
When uploading an image to openstack-glance, running under uwsgi fails with
no data. Trying to debug this, I see a <uwsgi._Input object at ...> but when
calling .read() on this object, no data is returned.

This works under gunicorn and apache/mod_wsgi

When I try instead to run uwsgi.chunked_read(), I get data.

Is not .read() supposed to work on uwsgi._Input objects?

**Comment by unbit** [comment]
WSGI does not have a standard for managing body without a valid Content-Length header.

The frontend webserver (nginx or apache) should fix it by buffering the chunked input. Maybe you are running uWSGI http router as the frontmost server ?

**Comment by bjne** [comment]
That is correct, in testing at the moment uWSGI is the http router.

**Comment by unbit** [comment]
In such a case you need to "override" the input reader code to use uwsgi.chunked_read() (but it is really very specific and probably suboptimal). Just place uWSGI behind nginx and it should work. If you cannot do it because you need uWSGI http router specific-features i strongly suggest you to drop a mail to info@unbit.it for a "sponsored" feature request (the http router buffering chunked input requests)

**Comment by bjne** [comment]
Thanks for the response. I will use nginx in front anyway, so will start there, and eventually
contact you guys for implementing this feature if needed.
