### ISSUE TITLE
Provide mechanism to detect if running inside uWSGI

### ISSUE THREAD

**Issue by akvadrako** [unbit/uwsgi#1319]
I would like to create one source file which may be either:

- run by uWSGI, in which case I want to register a timer
- imported by other files, for example unit tests

So what I need is a documented and stable way to detect if I'm running inside a uWSGI process. Something like a global variable or a function inside the uwsgi module would suffice.

**Comment by xrmx** [comment]
You forgot to mention the language you are working on :) Let's say you mean python, it is clearly stated in the documentation that the availability of the uwsgi module means you are running under uwsgi:
 http://uwsgi-docs.readthedocs.io/en/latest/PythonModule.html

**Comment by akvadrako** [comment]
It doesn't state that at all. It would be nice to state it.

**Comment by xrmx** [comment]
What about *as well as detecting whether you’re actually running under uWSGI* isn't clear?
Patches welcome of course

**Comment by akvadrako** [comment]
Indeed, it is strongly implied.

**Comment by megahall** [comment]
@xrmx The documentation says, "The uWSGI server automagically adds a uwsgi module into your Python apps." But it doesn't say, already imported, or not already imported, or any example or explanation how to try to see that it's there and do stuff or catch the failure. Nobody is saying it doesn't work, we're asking more clearly how it works so that somebody could actually use it.

**Comment by xrmx** [comment]
uwsgi makes the uwsgi python module *available* to your app so you can import it. If the import fails you are not running inside uwsgi. Feel free to open a PR for uwsgi-docs making it more clear.

**Comment by megahall** [comment]
Thanks Riccardo. I will work on a clarification. 

Matthew Hall
