### ISSUE TITLE
CGI sanitize file descriptors is too slow in some circumstances

### ISSUE THREAD

**Issue by fukanchik** [unbit/uwsgi#2053]
[This](https://github.com/unbit/uwsgi/blob/master/plugins/cgi/cgi_plugin.c#L782) block of code takes 1.5 seconds to execute under docker on my PROD machines:
```
for(i=3;i<(int)uwsgi.max_fd;i++) {
        close(i);
}
```

I don't have access rights necessary to debug this within the docker or debug the docker itself. I tried to reproduce this in other places where I can become root but it was not that bad.

When I replace that loop with reading available descriptors from `/proc/<pid>/fd` it works perfectly still successfully closing all the unwanted descriptors.

I suggest to replace that loop with reading from `/proc/<pid>/fd` on machines where `procfs` is available.

**Comment by bergerspencer** [comment]
I didn't benchmark how long the block of code takes, but I believe I have this issue too, not in docker, but in openindiana (SunOS). It may be worse in certain operating systems as I see no performance degradation in a Debian buster VM.

Long story short, in openindiana (but not in Debian), uwsgi's cgi plugin appears to be bottlenecked to the point that operations that run at very different speeds in fcgiwrap (or in Debian with uwsgi) end up performing about the same. I initially noticed something weird with embedding cgi_python, but the most illustrative example is bash cgi (because it's a lot faster than python cgi). It turns out that embedded python2/3 and bash cgi both bottleneck at just a little bit faster 

I tried simply commenting out that block of code, and it removes the bottleneck. This doesn't prove anything (cleanup code is important and inherently introduces a bit of slowdown), but I think it's dramatic enough to highly suggest my issue is the same as yours

cgi-bin=fcgiwrap, alt-cgi-bin=uwsgi

In openindina:
cgi-bin/test.cgi:  316.81 [#/sec]
alt-cgi-bin/test.cgi: 16.79 [#/sec]
alt-cgi-bin/test.cgi, after commenting out block of code: 241.4 [#/sec]

In Debian 10, fcgiwrap and uwsgi are competitive:
cgi-bin/test.cgi = 706 / sec
alt-cgi-bin/test.cgi = 585 / sec
(Don't take any of these absolute numbers seriously since this is just intended to be a relative comparison. I didn't even bother copying the exact same test.cgi bash script.)

I suspect some operations that are cheap on Linux aren't cheap everywhere. Wouldn't be the first time something like this has happened.

**Comment by awelzel** [comment]
Hey @bergerspencer / @fukanchik - random thought: Do you have a logline
```

**Comment by fukanchik** [comment]
what is logline?

**Comment by bergerspencer** [comment]
@awelzel, not such a random thought, can't believe I didn't notice that line and was copy pasting https://github.com/unbit/uwsgi/blob/3149df02ed443131c54ea6afb29fcbb0ed4d1139/core/master_utils.c#L510 into the cgi plugin

65536 (!!) - openindiana (kpti without pcid)
1024 - debian (amd, no kpti)

I guess just changing the limit to something reasonable will fix the major slowdown, but since you need root permissions to set it that may not help @fukanchik  

Over 60000 syscalls every request with kpti and without pcid would definitely kill your performance, but I'm not sure 1000 is a great idea either. Even in Debian without ktpi, commenting out the section makes uwsgi perform as good or better than fcgiwrap, while with the section it's at a significant disadvantage.

If you forked a special process to handle cgi requests, you could get away with only cleaning up like this once. Or if you expected only a small percentage of file descriptors to be open you could use poll and look for POLLNVAL to know which fds to close. 

I wonder if a pure python implementation that didn't have to clean up its fds every request would perform better...

**Comment by fukanchik** [comment]
In my case it's 
`detected max file descriptor number: 65536`

**Comment by rdeioris** [comment]
afaik on solaris-derived systems and bsds we could use closefrom()

**Comment by fukanchik** [comment]
libbsd's `closefrom` uses several approaches: starting from [`procfs`](https://github.com/freedesktop/libbsd/blob/master/src/closefrom.c#L127) if it's available and falling back to expensive [method](https://github.com/freedesktop/libbsd/blob/master/src/closefrom.c#L79).

**Comment by bergerspencer** [comment]
More numbers with/without kpti and with different max-fd values.

```
#req per second, kpti on / kpti off
#openindiana, no pcid
#ab -n 1000
fcgiwrap: 339.34 / 372.44
uwsgi (default 65536): 16.92 / 38.40
uwsgi (1024 max-fd): 188.95 / 217.65
uwsgi (256 max-fd): 218.43 / 242.02
uwsgi (16 max-fd): 229.88 / 253.55
uwsgi (commented out fd close): 257.70 /  282.51
uwsgi (closefrom(3)): 251.82 / 273.87

#debian VM on a different box, no kpti
#ab -n 10000
fcgiwrap: 738.42
uwsgi (default 1024): 619.87
uwsgi (256 max-fd): 700.25
uwsgi (16 max-fd): 716.20
uwsgi (commented out fd close): 756.97
```

@rdeioris 
closefrom(3) performs as well as not closing any file descriptors at all on my illumos box. 
But closing a bunch of fds every request does slow down linux too, just not as dramatically, if my tests are accurate.
If the user runs a separate uwsgi instance that only does cgi, it seems like it should be possible to fully account for the file descriptors and only close those that exist. But idk, maybe it's more trouble than it's worth. But it would be cool if uwsgi could outperform fcgiwrap on linux, as my tests seem to indicate is possible.
