### ISSUE TITLE
uwsgi queue bug

### ISSUE THREAD

**Issue by Laurel-rao** [unbit/uwsgi#2061]
Code below:
```
# uwsgi --http:6000 --processes=10 --threads=5 --wsgi-file=manage.py --queue=3 --queue-blocksize=4096

import uwsgi
from threading import Thread
from flask import Flask

app = Flask(__name__)

def show_queue():
    n = 0
    while True:
        res = uwsgi.queue_pull()
        if res:
            n += 1
            print("n == %s, res == %s"%(n, res))

t = Thread(target=show_queue)
t.setDaemon(True)
t.start()


@app.route("/hello/<name>/")
def hello(name):
    uwsgi.queue.push(name)
    return name
```

Then, i make the 10000 times requests，code below；
```

import requests
from threading import Thread

def req_queue(arg):
    resp = requests.get("http://127.0.0.1:6000/hello/%s/"%arg)
    print(resp.text)

T = []
for  i in range(10000):
    t = Thread(target=req_queue, args=(i, ))
    T.append(t)
    
for i in T:
    i.start()

for i in T:
    i.join()
```

The theoretical data with **n** should be equal10000 but through multiple tests, the real result always less 10000, the average is about 9950.
Please help solve this problem, i'll be grateful.

**Comment by awelzel** [comment]
Hey @Laurel-rao ,

that's an interesting experiment. I suspect you see n < 10000 as you run over the very small queue length of 3 at times (Check the 3rd sentence here https://uwsgi-docs.readthedocs.io/en/latest/Queue.html).

For example, if 4 threads complete the `uwsgi.queue.push(name)` operation but the `show_queue` thread isn't scheduled (no `uwsgi.queue.pull()` happened), you will effectively observe a lost entry.

In fact, if you were to run `show_queue()` only after all threads completed their word, you should observe n=3.

I believe this can be closed as it's expected behavior?

**Comment by Laurel-rao** [comment]
I can't understand the way that queue of uWSGI works.But i use the normal python queue, the result that i observed n = 10000. That I choose the other ways to complete my project, i'll close the issue.
