### ISSUE TITLE
On HTTP response, uWSGI (or Flask) seems to sleep exactly 1 sec.

### ISSUE THREAD

**Issue by akeyhero** [unbit/uwsgi#2129]
Apologies in advance if this is because of Flask.

I have noticed that when POSTing a file, "Flask with uWSGI @ HTTP" responses with an exactly 1 sec delay in contrast to "bare Flask" and "Flask with uWSGI @ WSGI".

## Experiment

Detailed in: https://github.com/akeyhero/uwsgi-http-is-slow

```
Flask==1.1.1
uwsgi==2.0.18
```

### Bare Flask

```bash
$ time curl -s -XPOST -F file=@LICENSE localhost:5001 > /dev/null
curl -s -XPOST -F file=@LICENSE localhost:5001 > /dev/null  0.01s user 0.01s system 30% cpu 0.067 total
```

### Flask with uWSGI @ HTTP

```bash
$ time curl -s -XPOST -F file=@LICENSE localhost:5002 > /dev/null
curl -s -XPOST -F file=@LICENSE localhost:5002 > /dev/null  0.01s user 0.01s system 1% cpu 1.063 total
```

### Flask with uWSGI @ WSGI (with nginx)

```bash
$ time curl -s -XPOST -F file=@LICENSE localhost:5003 > /dev/null
curl -s -XPOST -F file=@LICENSE localhost:5003 > /dev/null  0.01s user 0.01s system 31% cpu 0.062 total
```

**Comment by awelzel** [comment]
Hey @akeyhero ,

the delay is actually caused by `curl`: It sends a `Expect: 100-continue` header and waits for 1s for the server to respond with a `HTTP/1.1 100 Continue`. It only does this for PUT or POST with "large" files - see also [1].

If you look at the `-v` output from curl, you'll see the following:
```
...
> Content-Type: multipart/form-data; boundary=------------------------e982bffbb486e11e
> Expect: 100-continue
> 
* Expire in 1000 ms for 0 (transfer 0x5641c5a0af50)
* Done waiting for 100-continue
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
...
```

Flask and nginx handle `Expect: 100-continue` by default. With `uwsgi`. `curl` waits for 1s and then sends the POST anyway. For `uwsgi` to handle this and send `100 Continue`, add `http-manage-expect` to your config:

```
[http]
ini = :uwsgi
http = 0.0.0.0:80
http-manage-expect = 1
```

Alternatively, you can disable this for `curl` with: `-H 'Expect:'`.

Hope this helps - mind closing?


[1] https://gms.tf/when-curl-sends-100-continue.html

**Comment by akeyhero** [comment]
Hi, Awelzel

Thank you for a really kind reply and sorry for my poor understanding of `curl`.
I was one of the greatest learnings in this year thanks to you.
