### ISSUE TITLE
What is the status of this project's maintenance? Changes for easier contributing

### ISSUE THREAD

**Issue by tgross35** [unbit/uwsgi#2407]
Hey all,

Is this project looking for contributors/maintainers? It seems a bit stalled in development. Only about a dozen commits to master in the past year, 700 open issues out of 1600 total, dozens of PRs without any comments - doesn't indicate the most healthy project unfortunately. The github workflow doesn't even look like it has tests for python 3.9 or 3.10.

Anyway long story short, it seems like there could be some work to lower barriers to contributing. Just a CONTRIBUTING.md file would be a good first step!

Edit: I see #2287 mentioned something similar. The github sponsors is a great idea, lots of companies use uWSGI in production and would probably be happy to sponsor.

**Comment by rdeioris** [comment]
Hi @tgross35 i could say the the project is in maintenance-only mode. During the past years i moved to other works and with @xrmx we tried to do our best in keeping up with bugfixing and updates for newer python versions. Definitely i am not going to add more features to the project (i think it is more than 5 years that no feature has been added ;) and i am super-opened to new maintainers obviously. Unfortunately the codebase has more than 12 years, lacks a proper test coverage (i was young and irresponsible ;) and this caused the project to be be very hard to contribute to. From my point of view, revamping the project, means adding a proper test framework, otherwise is just frustration :(

**Comment by tgross35** [comment]
@rdeioris That's too bad to hear! I have enjoyed using uwsgi and know I am not alone, I hope you find a good maintainer to step up! I wish I could help but I don't know enough about anything wsgi related...

Maybe set up sponsors (mentioned here https://github.com/unbit/uwsgi/issues/2287#issuecomment-783272826) that go to bug bounties to drum up some interest. I'm sure some people would be willing to help, especially for some incentive.
