### ISSUE TITLE
Indication when request headers size is more than possible (64k)

### ISSUE THREAD

**Issue by adeptg** [unbit/uwsgi#355]
Now when request headers size is more than possible uwsgi just closes connection (TCP RST) and there is nothing interesting in logs that indicate about headers size. I think it will be great to write some info in log

**Comment by KatyaRuth** [comment]
I'd like to reopen this issue re: the original topic. If uwsgi is going to refuse to process a request because the Header Size, it should return an error that is informative around why it has closed the connection.

Similarly, I think that should extend to the `--limit-post` param as well. Right now,  if someone sends a request that is larger than the specified limit in this param, uwsgi just closes the connection, rather than returning something like a 413 RequestEntityTooLarge exception.

Having more informative failure states is useful for clients to understand their mistakes and improve their requests.
