### ISSUE TITLE
Max-requests causes all workers to be killed at around the same time

### ISSUE THREAD

**Issue by diwu1989** [unbit/uwsgi#648]
If I set the max-requests option, very often, all the workers are restarted at around the same time.

Is it possible to stagger the restart? I still need the max-requests feature, but if you initialize the number of requests handled by each worker by
1/ (N workers) \* max_requests
then the restarts will be spread out evenly.

**Comment by avish** [comment]
If I understand correctly, the implemented solution means that worker 0 will always have a lower effective max-requests setting, i.e. it will be recycled more often than worker N. This creates a persistent imbalance between workers.

The original proposal of initializing the requests counter of each worker with 1/N*maxRequests (or a configured delta) *only once* at the time of first forking, would have created a balanced situation where the first recycling is "unfair" (higher-numbered workers will get their first recycling earlier than lower-numbered workers) but *all subsequent recycles are fair* and happen after the exact same number of requests regardless of worker ID. In a long-running application which relies on periodic recycling, this balance is crucial. 

Another option is to allow a random offset to be added to max-requests per worker, per cycle. This is a weaker guarantee for balance between workers but will still avoid the problem of recycling all workers at the same time, while also not creating a persistent imbalance between workers.

Lastly, these techniques could also apply to the `max-worker-lifetime` option, except with time delta instead of requests delta.
