### ISSUE TITLE
Make pyuwsgi plugin python 3 compatible

### ISSUE THREAD

**Issue by msurdi** [unbit/uwsgi#816]

**Comment by unbit** [comment]
Do you use it or you are a packager ? I am asking because we were thinking about removing it, but if you have a use it for it we can start mantaining it again. Thanks

**Comment by msurdi** [comment]
I was just looking for a way to run uwsgi from a freezed (cx_freeze) application. TBH, this is just some experimentation so I'm not using it right now, just investigating if this could work in this setup so I can replace gunicorn.

**Comment by xtfxme** [comment]
I am using this. Combined with `setup.cpyext.py` in 2.1 you get a real python module, `uswgi.so`, and you can call `uwsgi.setup` return to python and do more work (in the master while interacting with uWSGI api) then call `uwsgi.run`.

IMO this should be the default for pip installations at the least, and fixes at least 2-3 pip related bugs in the tracker.

**Comment by funkybob** [comment]
Is this issue still outstanding, or has it been fixed?

**Comment by natefoo** [comment]
@unbit any chance this will see some work? If not, I have looked at it a bit, and can commit some more effort to it in a few months.

We do use pyuwsgi quite heavily, as it is (to my knowledge) the only way to provide a precompiled uwsgi that does not either: 1. require a dynamic libpython to be installed on the system, or 2. statically link libpython. This is how we build uWSGI wheels for [wheels.galaxyproject.org](https://wheels.galaxyproject.org) and aside from a few non-showstopping bugs, it works well for Python 2.

**Comment by ipmb** [comment]
For anybody keeping an eye on this issue (and wanting to build wheels), [Lincoln Loop](https://lincolnloop.com/) is sponsoring development for it. @unbit just [committed a fix for building pyuwsgi on Python 3](https://github.com/unbit/uwsgi/compare/9055cf1a0db63adaba21189099e96a953992fbb2...eebe9f251646e83c92669777a725cbd058c7f72f). From the `uwsgi-2.0` branch, the shared library can be built with:

```bash
UWSGI_EMBED_PLUGINS=python make pyuwsgi PYTHON=python3
```

but I'm hoping we can get to the point where that just happens as part of the pip install. 🤞

**Comment by natefoo** [comment]
@ipmb Great, this is [better than my efforts so far](https://travis-ci.org/natefoo/starforge-recipes/builds/426822660). Two potential outstanding issues with wheels in PyPI (that maybe should get their own issue(s) but I'm mentioning them here since you're currently working on the packaging):

1. There's not a great way with the standard PyPA tooling to provide wheels with differing functionality. Some, such as linking libpcre, is probably safe to include in all wheels since it only enables additional functionality but does not otherwise change the behavior of a non-PCRE build. But others, such as linking libyaml (#863), change the normal behavior in incompatible ways. To support both, uWSGI needs a switch to specify "use internal YAML parsing even if built with libyaml," but maybe there is some setuptools `extras_require` trick that can be used here (e.g. for `pip install pyuwsgi[libyaml]`).
2. It's not possible to bundle nonstandard libs into the macOS wheel currently (libyaml, libpcre, ...) due to a limitation in delocate described in [matthew-brett/delocate#12 (comment)](https://github.com/matthew-brett/delocate/issues/12#issuecomment-246536098) unless the pyuwsgi shared lib is placed inside a dummy package. It may make more sense to fix delocate rather than pyuwsgi, however.

**Comment by ipmb** [comment]
Thanks for the feedback @natefoo. I'm definitely fumbling my way through some of the packaging stuff, so your feedback is appreciated.

> There's not a great way with the standard PyPA tooling to provide wheels with differing functionality.

I'm leaning towards the wheel configuration being opinionated and if you want something different, you can always build your own from the sdist. My current thinking is to bundle zlib, pcre, libyaml, and jansson, but exclude ssl. Would that work for your use case?

> It's not possible to bundle nonstandard libs into the macOS wheel currently (libyaml, libpcre, ...) 

Shoot! I didn't realize that. I'm open to any ideas, that's beyond my area of expertise :)

Could you try out the latest wheels I uploaded and see how they work for you?

```
pip install -U --pre pyuwsgi
```

It might make sense to move discussion on the wheels to https://github.com/lincolnloop/pyuwsgi-wheels

**Comment by natefoo** [comment]
Thanks, I moved the other issues over to lincolnloop/pyuwsgi-wheels#1 and lincolnloop/pyuwsgi-wheels#2.

I tested two - both `pyuwsgi-2.0.17.2a4-cp27-cp27mu-manylinux1_x86_64.whl` and `pyuwsgi-2.0.17.2a4-cp35-cp35m-manylinux1_x86_64.whl` work for me.

**Comment by ipmb** [comment]
This issue can be closed. [pyuwsgi is available on PyPI](https://pypi.org/project/pyuwsgi/) and Python 3 compatible.

**Comment by xrmx** [comment]
Thanks for the update
