### ISSUE TITLE
fixcl will add second Content-Length header

### ISSUE THREAD

**Issue by funkybob** [unbit/uwsgi#846]
When a request has an existing Content-Length header, I would have expected flxcl route to "fix" it for the current content length.

Instead, it unilaterally appends a _new_ Content-Length header.

This can't be circumvented by remheader first, because that affects a blacklist of headers which fixcl abides by [indirectly by using uwsgi_response_add_header]

**Comment by unbit** [comment]
I am about to add a 'forcecl' rule, that is basically a 'fixcl' action but with forced status when adding the header (se the remheader will be ignored)

**Comment by unbit** [comment]
Check the test in the commit:

* with fixcl you will get no Content-Length (caused by remheader)
* without remheader and with fixcl you will get 3 headers (2 content-length by the scripts, one by the fixcl)
* with remheader and forcecl you will get 1 content-length (the app-related are swalloed, the forcecl is applied)
* without remheader and with forcecl you will get 3 headers again
